### ISSUE TITLE
Public link doesn't work on Synology host

### ISSUE THREAD

**Issue by Outclass0026** [cmintey/wishlist#188] opened 2024-12-08 12:11 UTC
**Describe the bug**
When accessing a public link, the host state the page doesn't exist.
It include invite users link and registry links.

It's probably more a Synology issue due to the reverse proxy not managing URL paths but if you have a solution on your end it would be very appreciated.

**To Reproduce**
- Setup your DNS correctly
- Deploy a container on a Synology host
- Configure the reverse proxy in advanced mode
- Add the custom headers for websocket

**Expected behavior**
- Public link working.

**Logs**
WRN WRN WRN WRN WRN WRN WRN WRN ts=1733658290.1142638 WRN WRN WRN WRN WRN WRN WRN WRN ts=1733658290.1142638 msg=failed to set GOMAXPROCS WRN WRN WRN WRN WRN WRN WRN WRN ts=1733658290.1142638 WRN WRN WRN WRN WRN WRN WRN WRN ts=1733658290.1142638 msg=failed to set GOMAXPROCS error=open /sys/fs/cgroup/cpu/cpu.cfs_quota_us: no such file or directory
WRN WRN WRN WRN WRN WRN WRN WRN ts=1733658290.158997 WRN WRN WRN WRN WRN WRN WRN WRN ts=1733658290.158997 msg=failed to set GOMAXPROCS WRN WRN WRN WRN WRN WRN WRN WRN ts=1733658290.158997 WRN WRN WRN WRN WRN WRN WRN WRN ts=1733658290.158997 msg=failed to set GOMAXPROCS error=open /sys/fs/cgroup/cpu/cpu.cfs_quota_us: no such file or directory
INF INF INF INF INF INF INF INF ts=1733658290.159545 INF INF INF INF INF INF INF INF ts=1733658290.159545 msg=using config from file INF INF INF INF INF INF INF INF ts=1733658290.159545 INF INF INF INF INF INF INF INF ts=1733658290.159545 msg=using config from file file=/usr/src/app/Caddyfile
INF INF INF INF INF INF INF INF ts=1733658290.1611853 INF INF INF INF INF INF INF INF ts=1733658290.1611853 msg=adapted config to JSON INF INF INF INF INF INF INF INF ts=1733658290.1611853 INF INF INF INF INF INF INF INF ts=1733658290.1611853 msg=adapted config to JSON adapter=caddyfile
WRN WRN WRN WRN WRN WRN WRN WRN ts=1733658290.161209 WRN WRN WRN WRN WRN WRN WRN WRN ts=1733658290.161209 msg=Caddyfile input is not formatted; run 'caddy fmt --overwrite' to fix inconsistencies WRN WRN WRN WRN WRN WRN WRN WRN ts=1733658290.161209 WRN WRN WRN WRN WRN WRN WRN WRN ts=1733658290.161209 msg=Caddyfile input is not formatted; run 'caddy fmt --overwrite' to fix inconsistencies adapter=caddyfile WRN WRN WRN WRN WRN WRN WRN WRN ts=1733658290.161209 WRN WRN WRN WRN WRN WRN WRN WRN ts=1733658290.161209 msg=Caddyfile input is not formatted; run 'caddy fmt --overwrite' to fix inconsistencies WRN WRN WRN WRN WRN WRN WRN WRN ts=1733658290.161209 WRN WRN WRN WRN WRN WRN WRN WRN ts=1733658290.161209 msg=Caddyfile input is not formatted; run 'caddy fmt --overwrite' to fix inconsistencies adapter=caddyfile file=/usr/src/app/Caddyfile WRN WRN WRN WRN WRN WRN WRN WRN ts=1733658290.161209 WRN WRN WRN WRN WRN WRN WRN WRN ts=1733658290.161209 msg=Caddyfile input is not formatted; run 'caddy fmt --overwrite' to fix inconsistencies WRN WRN WRN WRN WRN WRN WRN WRN ts=1733658290.161209 WRN WRN WRN WRN WRN WRN WRN WRN ts=1733658290.161209 msg=Caddyfile input is not formatted; run 'caddy fmt --overwrite' to fix inconsistencies adapter=caddyfile WRN WRN WRN WRN WRN WRN WRN WRN ts=1733658290.161209 WRN WRN WRN WRN WRN WRN WRN WRN ts=1733658290.161209 msg=Caddyfile input is not formatted; run 'caddy fmt --overwrite' to fix inconsistencies WRN WRN WRN WRN WRN WRN WRN WRN ts=1733658290.161209 WRN WRN WRN WRN WRN WRN WRN WRN ts=1733658290.161209 msg=Caddyfile input is not formatted; run 'caddy fmt --overwrite' to fix inconsistencies adapter=caddyfile file=/usr/src/app/Caddyfile line=2
WRN WRN WRN WRN WRN WRN WRN WRN ts=1733658290.161478 WRN WRN WRN WRN WRN WRN WRN WRN ts=1733658290.161478 logger=admin WRN WRN WRN WRN WRN WRN WRN WRN ts=1733658290.161478 WRN WRN WRN WRN WRN WRN WRN WRN ts=1733658290.161478 logger=admin msg=admin endpoint disabled
INF INF INF INF INF INF INF INF ts=1733658290.161656 INF INF INF INF INF INF INF INF ts=1733658290.161656 logger=tls.cache.maintenance INF INF INF INF INF INF INF INF ts=1733658290.161656 INF INF INF INF INF INF INF INF ts=1733658290.161656 logger=tls.cache.maintenance msg=started background certificate maintenance INF INF INF INF INF INF INF INF ts=1733658290.161656 INF INF INF INF INF INF INF INF ts=1733658290.161656 logger=tls.cache.maintenance INF INF INF INF INF INF INF INF ts=1733658290.161656 INF INF INF INF INF INF INF INF ts=1733658290.161656 logger=tls.cache.maintenance msg=started background certificate maintenance cache=0xc00066e580
INF INF INF INF INF INF INF INF ts=1733658290.1616917 INF INF INF INF INF INF INF INF ts=1733658290.1616917 logger=http.auto_https INF INF INF INF INF INF INF INF ts=1733658290.1616917 INF INF INF INF INF INF INF INF ts=1733658290.1616917 logger=http.auto_https msg=automatic HTTPS is completely disabled for server INF INF INF INF INF INF INF INF ts=1733658290.1616917 INF INF INF INF INF INF INF INF ts=1733658290.1616917 logger=http.auto_https INF INF INF INF INF INF INF INF ts=1733658290.1616917 INF INF INF INF INF INF INF INF ts=1733658290.1616917 logger=http.auto_https msg=automatic HTTPS is completely disabled for server server_name=srv0
INF INF INF INF INF INF INF INF ts=1733658290.1647797 INF INF INF INF INF INF INF INF ts=1733658290.1647797 logger=http.log INF INF INF INF INF INF INF INF ts=1733658290.1647797 INF INF INF INF INF INF INF INF ts=1733658290.1647797 logger=http.log msg=server running INF INF INF INF INF INF INF INF ts=1733658290.1647797 INF INF INF INF INF INF INF INF ts=1733658290.1647797 logger=http.log INF INF INF INF INF INF INF INF ts=1733658290.1647797 INF INF INF INF INF INF INF INF ts=1733658290.1647797 logger=http.log msg=server running name=srv0 INF INF INF INF INF INF INF INF ts=1733658290.1647797 INF INF INF INF INF INF INF INF ts=1733658290.1647797 logger=http.log INF INF INF INF INF INF INF INF ts=1733658290.1647797 INF INF INF INF INF INF INF INF ts=1733658290.1647797 logger=http.log msg=server running INF INF INF INF INF INF INF INF ts=1733658290.1647797 INF INF INF INF INF INF INF INF ts=1733658290.1647797 logger=http.log INF INF INF INF INF INF INF INF ts=1733658290.1647797 INF INF INF INF INF INF INF INF ts=1733658290.1647797 logger=http.log msg=server running name=srv0 protocols=["h1","h2","h3"]
INF INF INF INF INF INF INF INF ts=1733658290.165143 INF INF INF INF INF INF INF INF ts=1733658290.165143 msg=autosaved config (load with --resume flag) INF INF INF INF INF INF INF INF ts=1733658290.165143 INF INF INF INF INF INF INF INF ts=1733658290.165143 msg=autosaved config (load with --resume flag) file=/root/.config/caddy/autosave.json
INF INF INF INF INF INF INF INF ts=1733658290.1651535 INF INF INF INF INF INF INF INF ts=1733658290.1651535 msg=serving initial configuration
Successfully started Caddy (pid=13) - Caddy is running in the background
INF INF INF INF INF INF INF INF ts=1733658290.169473 INF INF INF INF INF INF INF INF ts=1733658290.169473 logger=tls INF INF INF INF INF INF INF INF ts=1733658290.169473 INF INF INF INF INF INF INF INF ts=1733658290.169473 logger=tls msg=cleaning storage unit INF INF INF INF INF INF INF INF ts=1733658290.169473 INF INF INF INF INF INF INF INF ts=1733658290.169473 logger=tls INF INF INF INF INF INF INF INF ts=1733658290.169473 INF INF INF INF INF INF INF INF ts=1733658290.169473 logger=tls msg=cleaning storage unit storage=FileStorage:/root/.local/share/caddy
INF INF INF INF INF INF INF INF ts=1733658290.1698196 INF INF INF INF INF INF INF INF ts=1733658290.1698196 logger=tls INF INF INF INF INF INF INF INF ts=1733658290.1698196 INF INF INF INF INF INF INF INF ts=1733658290.1698196 logger=tls msg=finished cleaning storage units
Prisma schema loaded from prisma/schema.prisma
Datasource "db": SQLite database "prod.db" at "file:/usr/src/app/data/prod.db?connection_limit=1"
26 migrations found in prisma/migrations
No pending migrations to apply.
Running seed command `node prisma/seed.js` ...
roles are synced
skipping default group creation
Patching item price model
0 items to update
Finished patching item price model
🌱  The seed command has been executed.
┌─────────────────────────────────────────────────────────┐
│  Update available 5.22.0 -> 6.0.1                       │
│                                                         │
│  This is a major update - please follow the guide at    │
│  https://pris.ly/d/major-version-upgrade                │
│                                                         │
│  Run the following to update                            │
│    npm i --save-dev prisma@latest                       │
│    npm i @prisma/client@latest                          │
└─────────────────────────────────────────────────────────┘
> wishlist@0.0.1 start /usr/src/app

> node build
Listening on 0.0.0.0:3000

**Screenshots**
![image](https://github.com/user-attachments/assets/d163237b-567d-470b-b30c-8d5b4ac6f2cb)
![image](https://github.com/user-attachments/assets/a5050c14-3980-4580-82a7-b7d4b4d7bfb9)

**Comment by cmintey** [comment] 2024-12-08 16:39
Your Synology proxy should be pointed to port 3280. I know it says the server is running on 3000, but Wishlist has its own proxy internally running on 3280. That's probably something I can address

**Comment by Outclass0026** [comment] 2024-12-08 16:46
Sorry I was doing a lot of tests and I pasted a wrong screenshot. I noticed it's only caddy that use the port 3000 and my configuration is pointing to 3280 port but it doesn't work anyway.
I edited my picture in the original post.

I noticed if I use https://wishlist.example.com/lists/uid I receive the "This page does not exist" from the Synology host.
If I go on https://myprivateip//lists/uid I receive the same message, but from the Container.

Thanks for your help

**Comment by cmintey** [comment] 2024-12-08 16:52
So you're not seeing this page? This is what I see if I enter a bad list id 
![image](https://github.com/user-attachments/assets/073d0eb3-a7e7-4acd-a1fc-82d21b409c1c)

**Comment by Outclass0026** [comment] 2024-12-08 16:56
With the domain name:
![image](https://github.com/user-attachments/assets/dc6712e1-ea35-470b-aea0-418c8c86105d)

With the domain name but with a bad ID list: Same as your picture

With the IP address:
![image](https://github.com/user-attachments/assets/2df6a103-1cb8-4919-a083-7b8205e71f30)

**Comment by cmintey** [comment] 2024-12-08 17:18
That's really strange. I'm not able to reproduce. I don't know why your container is returning differently with a good vs bad list id. Can you share your docker compose and env variables? And just to confirm, you don't see any additional logs in the container, correct? Any logs from the Synology proxy?

**Comment by zlatanlover** [comment] 2024-12-08 17:19
> With the domain name: ![image](https://private-user-images.githubusercontent.com/77553712/393625460-dc6712e1-ea35-470b-aea0-418c8c86105d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2Nzg2NDIsIm5iZiI6MTczMzY3ODM0MiwicGF0aCI6Ii83NzU1MzcxMi8zOTM2MjU0NjAtZGM2NzEyZTEtZWEzNS00NzBiLWFlYTAtNDE4YzhjODYxMDVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA4VDE3MTkwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyYWJjMTQzNjI4ZmM1MWU1MWVmZDZkMjQzMTgxMjIyODExODNkMWYwYTVkMGI1NDQ0OTBmNThlMDU5NTYzMDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.J5zoaI-fklQOtFD4ZiIvXqz2fLsbk4ZVIPGSgVsmhtI)
> 
> With the domain name but with a bad ID list: Same as your picture
> 
> With the IP address: ![image](https://private-user-images.githubusercontent.com/77553712/393625303-2df6a103-1cb8-4919-a083-7b8205e71f30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2Nzg2NDIsIm5iZiI6MTczMzY3ODM0MiwicGF0aCI6Ii83NzU1MzcxMi8zOTM2MjUzMDMtMmRmNmExMDMtMWNiOC00OTE5LWEwODMtN2I4MjA1ZTcxZjMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA4VDE3MTkwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0MmVhNWQwOTJkNTY2M2ExYzczMzVhZGZiYzMxZDE4YWYxODNjMzY5NWY2MzRhZDliMDg2ZDJiMzM2YWNiYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.oZM1WgljEYPJVxKwprb7Sl6KOl0Zo4NshNdpFrZGRmo)

I have exactly the same with my Synology NAS. It used to work before. Only the public link is not working.

**Comment by cmintey** [comment] 2024-12-08 17:24
Before, as in say last week before the latest release? If so, can you try using image tag `v0.35.0` and see if that works?

**Comment by Outclass0026** [comment] 2024-12-08 17:28
I'm using Portainer so I don't use .env file but here is the Docker compose:
`services:
  wishlist:
    container_name: wishlist
    image: ghcr.io/cmintey/wishlist:latest
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/3280' || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    ports:
      - 3280:3280
    volumes:
      - /volume1/docker/wishlist/uploads:/usr/src/app/uploads:rw
      - /volume1/docker/wishlist/data:/usr/src/app/data:rw
    environment:
      ORIGIN: https://wishlist.domain.xyz
      TOKEN_TIME: 72 # hours until signup and password reset tokens expire
      DEFAULT_CURRENCY: EUR`

I see more error now in the container but can I drop you these in private?
I don't want to expose my real domain and the names in the Wishlist in public.
I will try to redeploy the container in the previous version too as requested.

**Comment by cmintey** [comment] 2024-12-08 17:39
sure, if you have discord, you can drop me a message, username is `cmintey`

**Comment by Outclass0026** [comment] 2024-12-08 17:44
I sent the request for sending the logs and I confirm everything is working in the previous version!

**Comment by cmintey** [comment] 2024-12-11 00:58
Thanks for the assistance @Outclass0026. Turns out there was an issue with one of the dependencies. Upgrading to the latest has resolved the issue. This will be fixed in Wishlist v0.36.2

**Closed by cmintey** 2024-12-11 00:58 UTC
Labels: bug
